#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"
require_relative "../lib/soul_core/perception_readiness_assessor"

puts JSON.pretty_generate(SoulCore::PerceptionReadinessAssessor.new(root: File.expand_path("..", __dir__)).assess)
